### ISSUE TITLE
dnaPT_landscapes.sh running error

### ISSUE THREAD

**Issue by Liuxuanzeng** [clemgoub/dnaPT_utils#1]
output folder:      /home/liuxuanzeng/dnaPipeTE/
output prefix:      dnaPipeTE
super-family level: TRUE
custom ylim:        FALSE
plotting Unknown:   TRUE
[1] "load variables..."
Error in col.lands[i] <- cols$V2[grep(pattern = paste("^", levels(as.factor(land$TE_superfamily))[i],  : 
The length of the replacement parameter is zero  
Stop the execution 

I did a search, and maybe the error was running out of variable parameters.
I don't know what to do. Ask for help.
Thanks!

**Comment by clemgoub** [comment]
Hello @Liuxuanzeng,

I'm sorry you are having trouble with this script. Would you mind sharing the first few lines of the files:
- `Annotation/one_RM_hit_per_Trinity_contigs`
- `Annotation/sorted_blast3`
located in the dnaPipeTE output folder?

Thanks and sorry again for the issue.

Best,

Clément

**Comment by Liuxuanzeng** [comment]
> Hello @Liuxuanzeng,
> 
> I'm sorry you are having trouble with this script. Would you mind sharing the first few lines of the files:
> 
>     * `Annotation/one_RM_hit_per_Trinity_contigs`
> 
>     * `Annotation/sorted_blast3`
>       located in the dnaPipeTE output folder?
> 
> 
> Thanks and sorry again for the issue.
> 
> Best,
> 
> Clément

Hello，
Thanks for helping me.
Here is my command to run the script.
$./dnaPT_landscapes.sh -I /home/liuxuanzeng/Project/loucust_0.2x_0.3t_350bp_lib/ -o /home/liuxuanzeng/dnaPipeTE/ -U 
I have this file Annotation/one_RM_hit_per_Trinity_contigs and sorted_blast3 in my results.
I don't think it's a problem with the script and input commands, because when I run dnaPipeTE with 0.1x data with a small amount of data, dnaPT_landscapes.sh runs fine. When I use 0.3x to run dnaPipeTE, and then run dnaPT_landscapes.sh, the above prompt error will appear. 
The same problem occurs with dnaPT_charts.sh. The result of large data volume cannot run. When I use -t to limit the threshold, it can run. Below is an example.
![图片](https://user-images.githubusercontent.com/109024718/178384191-0d17d16a-1d13-41f5-8fa8-302383e452da.png)
![图片](https://user-images.githubusercontent.com/109024718/178386605-4d985209-46a8-41d7-9cfd-274ba52ba593.png)


I think this error may be caused by the size of the data, maybe the number of contigs or the size of the sorted_blast3 result.
Thank you for your willingness to help me with my questions.

**Comment by Liuxuanzeng** [comment]
Hello，
Thanks for helping me.
Here is my command to run the script.
$./dnaPT_landscapes.sh -I /home/liuxuanzeng/Project/loucust_0.2x_0.3t_350bp_lib/ -o /home/liuxuanzeng/dnaPipeTE/ -U
I have this file Annotation/one_RM_hit_per_Trinity_contigs and sorted_blast3 in my results.
I don't think it's a problem with the script and input commands, because when I run dnaPipeTE with 0.1x data with a small amount of data, dnaPT_landscapes.sh runs fine. When I use 0.3x to run dnaPipeTE, and then run dnaPT_landscapes.sh, the above prompt error will appear.
The same problem occurs with dnaPT_charts.sh. The result of large data volume cannot run. When I use -t to limit the threshold, it can run. Below is an example.
![图片](https://user-images.githubusercontent.com/109024718/178388362-9f1c0f33-d058-4911-8b09-9c8bb3b4df7c.png)


I think this error may be caused by the size of the data, maybe the number of contigs or the size of the sorted_blast3 result.
Thank you for your willingness to help me with my questions.

**Comment by filonico** [comment]
Hi Clément,

I'm from the issue clemgoub/dnaPipeTE#70 and I'm getting the same error. Here are the first 10 lines of `Annotation/one_RM_hit_per_Trinity_contigs`:
```
comp_TRINITY_DN0_c0_g1_i1	305	0.3114754098360656	DNA5-1_LMi	DNA	4885	[1-94]	0.019037871033776868	
comp_TRINITY_DN1001_c0_g1_i1	322	0.049689440993788817	(CTA)n	Simple_repeat	17	[1-17]	0.9411764705882353	
comp_TRINITY_DN1002_c0_g1_i1	426	0.9976525821596244	Polinton-10_NVi	DNA/Maverick	16575	[2838-3342]	0.030407239819004526	
comp_TRINITY_DN1002_c0_g1_i2	345	0.8724637681159421	Polinton-10_NVi	DNA/Maverick	5601	[2838-3107]	0.048027138011069455	
comp_TRINITY_DN1002_c0_g2_i1	219	0.4840182648401826	Polinton-3_NV	DNA/Maverick	16575	[3082-3188]	0.006395173453996984	
comp_TRINITY_DN1003_c0_g1_i1	357	0.13165266106442577	(CAGG)n	Simple_repeat	325	[1-191]	0.5846153846153846	
comp_TRINITY_DN1003_c0_g1_i2	341	0.04105571847507331	(CAGG)n	Simple_repeat	315	[1-315]	0.9968253968253968	
comp_TRINITY_DN1003_c0_g1_i3	360	0.15833333333333333	(CAGG)n	Simple_repeat	344	[5-344]	0.9854651162790697	
comp_TRINITY_DN1003_c0_g1_i4	334	0.9131736526946108	(CAGG)n	Simple_repeat	294	[1-294]	0.9965986394557823	
comp_TRINITY_DN1003_c0_g1_i5	338	0.04142011834319527	(CAGG)n	Simple_repeat	313	[1-60]	0.18849840255591055
```
and of `Annotation/sorted_blast3`:
```
130982	comp_TRINITY_DN0_c0_g1_i1	100.00	92	0	0	10	101	240	149	8e-43	 167
137823	comp_TRINITY_DN0_c0_g1_i1	96.55	87	3	0	1	87	159	245	9e-36	 143
168203	comp_TRINITY_DN0_c0_g1_i1	99.01	101	1	0	1	101	120	220	4e-46	 178
172372	comp_TRINITY_DN0_c0_g1_i1	76.14	88	13	1	14	93	246	159	6e-13	68.0
226497	comp_TRINITY_DN0_c0_g1_i1	97.73	44	1	0	58	101	245	202	4e-15	75.2
291149	comp_TRINITY_DN0_c0_g1_i1	98.18	55	1	0	1	55	186	240	4e-21	95.1
291679	comp_TRINITY_DN0_c0_g1_i1	100.00	67	0	0	35	101	1	67	3e-29	 122
358623	comp_TRINITY_DN0_c0_g1_i1	99.01	101	1	0	1	101	17	117	4e-46	 178
41040	comp_TRINITY_DN0_c0_g1_i1	99.01	101	1	0	1	101	102	202	4e-46	 178
44605	comp_TRINITY_DN0_c0_g1_i1	98.18	55	1	0	47	101	1	55	4e-21	95.1
```
Thank you very much!

**Comment by clemgoub** [comment]
Hello both of you @Liuxuanzeng and @filonico,

I can try to debug this for you (though I will be out of the office until next week). The best would be that you compress and send me a link to download the full output folder of your dnaPipeTE runs that cause the script to fail (my email is available in [my profile page](https://github.com/clemgoub)). I will try on my end and see if I can fix the error!

Best,

Clément

**Comment by clemgoub** [comment]
Dear @filonico and @Liuxuanzeng, I have found and fixed the problem! It was not related to data size, but to the presence of "RNA" category that was not listed in the colors' dictionary. I tested and on @filonico data and it works. 

Please pull the repos and retry!

@Liuxuanzeng if the issue persist, please reopen the thread and send me a compressed version of your output folder!

Cheers,

Clément

**Comment by Liuxuanzeng** [comment]
Hello Clément,
Thanks for your help, and very sorry for my wrong guess.
My output folder is trying to send via email. If it's too big to send, can I send you the input data (.fq)?

Thank you vary much.
Liuxuanzeng

**Comment by clemgoub** [comment]
Hello @Liuxuanzeng,
No problem at all! Can you try to send your data using a file sharing such as Wetransfer, or equivalent?

Cheers,

Clément
