### ISSUE TITLE
There may be a column name error in A_B_comparison_table.txt in the dnaPT_compare.sh result

### ISSUE THREAD

**Issue by Liuxuanzeng** [clemgoub/dnaPT_utils#2]
Hello Clément,
Below is the command I run dnaPT_compare.sh and the result file of A_B_comparison_table.txt.
![图片](https://user-images.githubusercontent.com/109024718/179640901-a940a782-8888-4841-b9ea-e7e8b5e8b4f1.png)
![图片](https://user-images.githubusercontent.com/109024718/179641197-a2b62410-7981-4e4d-89e3-d4e25094c883.png)
There are two reasons why I think the result file column names of comparison_table.txt might be wrong.
 
1.When the genome proportion in the first column of Locus is 0, the consensus sequence is Locus_Trinity_....... When Angar's genome proportion is 0, the consensus sequence is Angar_Trinity_.......
 
2.Calculations of the genome sizes of the two species also reflect this problem
Take this sequence as an example.
![图片](https://user-images.githubusercontent.com/109024718/179642244-bb48dfa1-c547-46b5-a1b2-241be3fc7ff9.png)
 
My input data is
Locus 6,600,000,000     0.1x
Angar 16,360,000,000   0.1x
 
When I use Locus_bp / Locus in table the result is    1232187/(0.07581995*0.01)=1,625,148,789.995245
This result should be Angar's genome size
 
When I use Angar_bp / Angar in table the result is 168959/(0.02577052*0.01) =655,628,990.0242603
This result should be Locus's genome size
 
The wrong column names for this table also lead to wrong names for the x-axis and y-axis in the .pdf file in the plot.
 
Thank you very much for helping me.
 
Liuxuanzeng

**Comment by clemgoub** [comment]
Dear @Liuxuanzeng,

Sorry for the issue. Indeed it seems that an inversion occurred somewhere. I tried to replicate the error with some of my data, but it was correct on my end. Would you mind sending me your output folder for each species so I can try to debug it?

Thanks,

Clément

**Comment by Liuxuanzeng** [comment]
Dear Clément
I'm trying to upload data to Google Drive, which contains the output files for each of the two species and the command  when I run dnaPT_compare.sh. I will then email you the share link.

Thank you very much!

Liuxuanzeng

**Comment by clemgoub** [comment]
Great! Let me know when it's ready, I'll look at it!

**Comment by clemgoub** [comment]
Dear @Liuxuanzeng,

I've been working on replicating the bug, but with my test data it the inversion doesn't happen. I am trying with a subset of your data now, but cd-hit is still running.

I noticed that your screenshot shows a re-run (i.e. the clustering was already performed). Could it be that at the time of the original clustering, the command you used had -A and -B inverted (but -a and -b the same)? The script goes within each output folder in the file `Count.txt` to extract the read count. I see that they are correct within each of those you send me. This could explain why the clustering file shall have the same name but not the actual data to normalize when you re-run with the correct order. 

The best way would be that you rename or delete completely the output folder (`-o`) and rerun the exact same command as in the screenshot. Also, could you send me before you delete the output the file "Locus_Angar_R.tsv"; so I will double check.

Best,

Clément

**Comment by Liuxuanzeng** [comment]
Dear Clément

I will try your suggestion to run again.The output the file "Locus_Angar_R.tsv" will be sent to you by email later.

Thank you very much!

Liuxuanzeng

**Comment by clemgoub** [comment]
Hi Liuxuanzeng,

Can you let me know if the issue persists? Please re-open the issue if you still have the problem.

Best,

Clément
