### ISSUE TITLE
error with dnaPT_charts.sh

### ISSUE THREAD

**Issue by sigau** [clemgoub/dnaPT_utils#3]
Hi !

I was trying to get the graphics for an dnapipeTE output but I get an error while running dnaPT_charts.sh. 

here is the command I use : 
dnaPT_charts.sh -I final_dnapipete_output -p Anopheles_gambiae_test

And here the result/error : 

input dataset:      final_dnapipete_output
output folder:      final_dnapipete_output
output prefix:      Anopheles_gambiae_test
custom ylim:        FALSE
── Attaching packages ───── tidyverse 1.3.1 ──
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
✔ purrr   0.3.4     
── Conflicts ──────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Error:
! objet 'V6' introuvable
Backtrace:
     ▆
  1. ├─tidyr::separate(...)
  2. ├─tidyr:::separate.data.frame(...)
  3. │ └─tidyselect::vars_pull(names(data), !!enquo(col))
  4. │   ├─tidyselect:::with_entraced_errors(...)
  5. │   │ └─rlang::try_fetch(...)
  6. │   │   └─base::withCallingHandlers(...)
  7. │   └─rlang::eval_tidy(enquo(var), set_names(seq_along(vars), vars))
  8. └─base::.handleSimpleError(...)
  9.   └─rlang h(simpleError(msg, call))
 10.     └─handlers[[1L]](cnd)
 11.       └─rlang::abort(conditionMessage(cnd), call = conditionCall(cnd))
Exécution arrêtée
All done, results in final_dnapipete_output/

Do you know how I can correct this ?

Thanks in advance,
Gautier

PS: When searching for this error I found this topic maybe it can help (https://community.rstudio.com/t/the-function-dplyr-filter-is-masked-by-stats-filter-how-to-change-it/17673)

**Comment by clemgoub** [comment]
Dear Gautier,

Thanks for reaching out. My gut feeling is that the dplyr/tidyverse conflict should not be a problem, rather, it may be related to the inputs (maybe something in your run caused the V6 column to be absent). The best way would be for me to test it with my local installation, if that's ok with you. If you don't mind sharing with me your output folder in a compressed format, I will look at it right away.

Can you tell me what is the machine and shell you are using to run this script?

I will also re-write the code trying to avoid the package maskings.

Cheers,

Clément

**Comment by sigau** [comment]
Hi !

Thank for you answer.
So i'm running it with bash on a cluster with debian (LBBE Cluster).
There is no problem for the data : 
https://filesender.renater.fr/?s=download&token=25342c6e-ba51-491e-85c4-35ac8072cce4

The script I use for running dnapipeTe is inside (script_dnapipete.sh) and I run it with the docker/singularity img and an update of repeat masker library with Repbase.

 Thanks in advance,
Gautier

**Comment by clemgoub** [comment]
Merci Gautier,

I'll check it ASAP!

Clém

**Comment by clemgoub** [comment]
**It's fixed!** You can pull the repository to get the updated script!

- There was a bug if the first line of the input table had no annotation, the table would be trimmed to only 3 columns which would eventually lead the `separate()` command to fail as it is intended to act on the 6th column.

- You may still see the `tidyr` masking warning, but it doesn't affect the script execution.

Thanks again for reaching out, it helps a lot curbing out these annoying bugs!

Clém
